- type: web
    name: vsdms-frontend
    runtime: node
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start -- -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false